version: "2.3"

services:
    esp_robocraft-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        network_mode: bridge
        environment:
          - PREFIX=${PREFIX:-~/.local}
          - CCACHE_DIR=/esp_robocraft/.ccache
          - CORES_DIR=/cores
        volumes:
          - .:/esp_robocraft:rw
        ports:
          - 8080:8080
        working_dir: /esp_robocraft
        entrypoint:
          - ./tests/run_as_user.sh
